const PERFORMANCE_REVIEWS_STORAGE_KEY="adt7j_performance_reviews_v1";
const REVIEW_IDMAP_KEY="adt7j_performance_reviews_idmap_v1";
let _editingReviewId=null;
function getStoredPerformanceReviews(){try{return JSON.parse(localStorage.getItem(PERFORMANCE_REVIEWS_STORAGE_KEY)||"[]")}catch(e){return[]}}
function saveStoredPerformanceReviews(v){localStorage.setItem(PERFORMANCE_REVIEWS_STORAGE_KEY,JSON.stringify(v||[]))}
function reviewUserKey(v){return normaliseKPIUserName(v)}
function getReviewUserScope(){return currentUser&&currentUser.Role!=="Admin"?(currentUser.Title||currentUser.Email||""):"all"}
function populateReviewBDMSelect(){const el=document.getElementById("reviewBDMSelect");if(!el)return;const users=getStoredUsers().filter(u=>String(u.Role||"BDM").toLowerCase()!=="admin");const merged=[...users];if(currentUser&&currentUser.Role!=="Admin"&&!merged.some(u=>reviewUserKey(u.Title||u.Email)===reviewUserKey(currentUser.Title||currentUser.Email)))merged.push(currentUser);el.innerHTML=merged.map(u=>`<option value="${escapeHtml(u.Title||u.Email||"")}">${escapeHtml(u.Title||u.Email||"")}</option>`).join("")}
function reviewToFields(r){return{Title:r.BDMName||r.BDMEmail||"BDM Review",ReviewId:String(r.Id),BDMName:r.BDMName||"",BDMEmail:r.BDMEmail||"",ReviewDate:r.ReviewDate||new Date().toISOString(),ReviewPeriod:r.ReviewPeriod||"monthly",Target:r.Target||"",AdminNote:r.AdminNote||"",BDMResponse:r.BDMResponse||"",ResponseDate:r.ResponseDate||"",AdminBy:r.AdminBy||"",Updated:r.Updated||new Date().toISOString(),UpdatedBy:r.UpdatedBy||""}}
function fieldsToReview(it){const f=it.fields||{};return{Id:String(f.ReviewId||it.id),BDMName:f.BDMName||f.Title||"",BDMEmail:f.BDMEmail||"",ReviewDate:f.ReviewDate||it.createdDateTime||"",ReviewPeriod:f.ReviewPeriod||"monthly",Target:f.Target||"",AdminNote:f.AdminNote||"",BDMResponse:f.BDMResponse||"",ResponseDate:f.ResponseDate||"",AdminBy:f.AdminBy||"",Updated:f.Updated||it.lastModifiedDateTime||"",UpdatedBy:f.UpdatedBy||"",spId:it.id,etag:it["@odata.etag"]}}
async function cloudLoadPerformanceReviews(){const sid=await getSiteId(),listId=await resolveListId(getListName("performanceReviews"));let url=`${GRAPH_BASE}/sites/${sid}/lists/${listId}/items?expand=fields&$top=500`,out=[],map={};while(url){const data=await graphGet(url);(data.value||[]).forEach(it=>{const r=fieldsToReview(it);out.push(r);map[r.Id]=it.id});url=data["@odata.nextLink"]||null}localStorage.setItem(REVIEW_IDMAP_KEY,JSON.stringify(map));return out.sort((a,b)=>new Date(b.ReviewDate)-new Date(a.ReviewDate))}
async function cloudPushPerformanceReview(r){const sid=await getSiteId(),listId=await resolveListId(getListName("performanceReviews")),map=JSON.parse(localStorage.getItem(REVIEW_IDMAP_KEY)||"{}"),fields=reviewToFields(r),spId=map[r.Id];if(spId)await graphPatch(`${GRAPH_BASE}/sites/${sid}/lists/${listId}/items/${spId}/fields`,fields);else{const created=await graphPost(`${GRAPH_BASE}/sites/${sid}/lists/${listId}/items`,{fields});if(created?.id){map[r.Id]=created.id;localStorage.setItem(REVIEW_IDMAP_KEY,JSON.stringify(map))}}}
async function loadPerformanceReviews(){if(isDemoMode()||!m365Configured()){renderPerformanceReviews();return}try{saveStoredPerformanceReviews(await cloudLoadPerformanceReviews())}catch(e){console.warn("Performance Reviews load failed:",e.message||e)}renderPerformanceReviews()}
function clearPerformanceReviewForm(){_editingReviewId=null;const d=document.getElementById("reviewDate");if(d)d.value=new Date().toISOString().slice(0,10);["reviewTarget","reviewAdminNote"].forEach(id=>{const e=document.getElementById(id);if(e)e.value=""});const p=document.getElementById("reviewPeriod");if(p)p.value="monthly"}
async function savePerformanceReview(){if(currentUser?.Role!=="Admin"){alert("Only administrators can create performance reviews.");return}const bdm=document.getElementById("reviewBDMSelect")?.value||"",target=document.getElementById("reviewTarget")?.value.trim()||"",note=document.getElementById("reviewAdminNote")?.value.trim()||"";if(!bdm||(!target&&!note)){alert("Select a BDM and enter a target or admin note.");return}const u=getStoredUsers().find(x=>reviewUserKey(x.Title||x.Email)===reviewUserKey(bdm)),id=_editingReviewId||("review-"+Date.now()+"-"+Math.floor(Math.random()*1000)),rows=getStoredPerformanceReviews(),old=rows.find(x=>String(x.Id)===String(id));const review={Id:id,BDMName:bdm,BDMEmail:u?.Email||"",ReviewDate:document.getElementById("reviewDate")?.value||new Date().toISOString().slice(0,10),ReviewPeriod:document.getElementById("reviewPeriod")?.value||"monthly",Target:target,AdminNote:note,BDMResponse:old?.BDMResponse||"",ResponseDate:old?.ResponseDate||"",AdminBy:currentUser?.Email||currentUser?.Title||"Admin",Updated:new Date().toISOString(),UpdatedBy:currentUser?.Email||""};const ix=rows.findIndex(x=>String(x.Id)===String(id));if(ix>=0)rows[ix]=review;else rows.unshift(review);saveStoredPerformanceReviews(rows);renderPerformanceReviews();logAuditRecord({Id:review.Id,Title:review.BDMName,Company:"Performance Review"},ix>=0?"PERFORMANCE_REVIEW_UPDATED":"PERFORMANCE_REVIEW_CREATED",`${ix>=0?"Updated":"Created"} performance review for ${bdm}`);if(!isDemoMode()&&m365Configured()){try{await cloudPushPerformanceReview(review)}catch(e){console.warn("Review cloud save failed:",e.message||e)}}_editingReviewId=null;const st=document.getElementById("reviewAdminStatus");if(st)st.textContent=isDemoMode()?"Review saved in Demo Mode.":"Review saved to Microsoft Lists."}
function renderPerformanceReviews(){const list=document.getElementById("performanceReviewList");if(!list)return;const admin=currentUser?.Role==="Admin",tools=document.getElementById("performanceReviewAdminTools");if(tools)tools.style.display=admin?"block":"none";populateReviewBDMSelect();const all=getStoredPerformanceReviews(),scope=getReviewUserScope(),rows=scope==="all"?all:all.filter(r=>reviewUserKey(r.BDMName)===reviewUserKey(scope)||reviewUserKey(r.BDMEmail)===reviewUserKey(currentUser?.Email));if(!rows.length){list.innerHTML='<div style="padding:24px;text-align:center;color:var(--muted);">No performance reviews yet.</div>';return}list.innerHTML=rows.map(r=>{const response=admin?"":`<div class="review-response-box"><label>Your response</label><textarea id="reviewResponse_${escapeHtml(String(r.Id))}" rows="3" placeholder="Respond to this review...">${escapeHtml(r.BDMResponse||"")}</textarea><button class="btn" type="button" onclick="respondToPerformanceReview('${String(r.Id).replace(/'/g,"\\'")}')">${r.BDMResponse?"Update response":"Respond"}</button>${r.ResponseDate?`<small>Last response ${new Date(r.ResponseDate).toLocaleString("en-GB")}</small>`:""}</div>`;const action=admin?`<button class="btn secondary" type="button" onclick="editPerformanceReview('${String(r.Id).replace(/'/g,"\\'")}')">Edit</button>`:"";return`<article class="performance-review-card"><div class="review-card-head"><div><strong>${escapeHtml(r.BDMName||"BDM")}</strong><small>${escapeHtml(r.ReviewPeriod||"")} · ${escapeHtml(r.ReviewDate||"")}</small></div><span class="review-status">${r.BDMResponse?"Responded":"Awaiting response"}</span></div>${r.Target?`<div class="review-block"><b>Target / objective</b><div>${escapeHtml(r.Target)}</div></div>`:""}${r.AdminNote?`<div class="review-block"><b>Admin notes</b><div>${escapeHtml(r.AdminNote)}</div><small>By ${escapeHtml(r.AdminBy||"Admin")} · ${new Date(r.Updated||r.ReviewDate).toLocaleString("en-GB")}</small></div>`:""}${r.BDMResponse?`<div class="review-block review-response"><b>BDM response</b><div>${escapeHtml(r.BDMResponse)}</div><small>${r.ResponseDate?new Date(r.ResponseDate).toLocaleString("en-GB"):""}</small></div>`:""}${response}${action?`<div style="margin-top:10px">${action}</div>`:""}</article>`}).join("")}
function editPerformanceReview(id){if(currentUser?.Role!=="Admin")return;const r=getStoredPerformanceReviews().find(x=>String(x.Id)===String(id));if(!r)return;_editingReviewId=r.Id;document.getElementById("reviewBDMSelect").value=r.BDMName;document.getElementById("reviewDate").value=String(r.ReviewDate||"").slice(0,10);document.getElementById("reviewTarget").value=r.Target||"";document.getElementById("reviewPeriod").value=r.ReviewPeriod||"monthly";document.getElementById("reviewAdminNote").value=r.AdminNote||"";document.getElementById("performanceReviewAdminTools")?.scrollIntoView({behavior:"smooth",block:"start"})}
async function respondToPerformanceReview(id){if(!currentUser||currentUser.Role==="Admin")return;const r=getStoredPerformanceReviews().find(x=>String(x.Id)===String(id));if(!r)return;if(reviewUserKey(r.BDMName)!==reviewUserKey(currentUser.Title||currentUser.Email)&&reviewUserKey(r.BDMEmail)!==reviewUserKey(currentUser.Email))return;const text=document.getElementById("reviewResponse_"+CSS.escape(String(id)))?.value.trim()||"";if(!text){alert("Enter a response first.");return}r.BDMResponse=text;r.ResponseDate=new Date().toISOString();r.Updated=r.ResponseDate;r.UpdatedBy=currentUser.Email||currentUser.Title||"";const rows=getStoredPerformanceReviews(),ix=rows.findIndex(x=>String(x.Id)===String(id));if(ix>=0)rows[ix]=r;saveStoredPerformanceReviews(rows);renderPerformanceReviews();logAuditRecord({Id:r.Id,Title:r.BDMName,Company:"Performance Review"},"PERFORMANCE_REVIEW_RESPONSE",`BDM response added by ${currentUser.Title||currentUser.Email}`);if(!isDemoMode()&&m365Configured()){try{await cloudPushPerformanceReview(r)}catch(e){console.warn("Review response cloud save failed:",e.message||e)}}}
